name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        shard: [1/6, 2/6, 3/6, 4/6, 5/6, 6/6] # Splits the tests into 6 parallel shards
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress

      - name: Install Cypress if not cached
        run: npx cypress install

      - name: Make Cypress Binary Executable
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress Tests (Parallel)
        run: npx cypress run --record --parallel --ci-build-id ${{ github.run_id }} --group ${{ matrix.shard }}
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        run: npm run headless